# Generated by Django 4.2.3 on 2023-08-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='price',
            field=models.IntegerField(),
        ),
    ]
